apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mondasample
  namespace: argo
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/jesusmonda/bootstrap-argocd-gatewayapi-kro.git
      targetRevision: main
      path: repos/team-2/mondasample
      directory:
        exclude: 'argocd.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2